### ISSUE TITLE
Unexpected letter 'n' in message pack parse result 

### ISSUE THREAD

**Issue by matthaeis** [niranjannitesh/react-native-msgpack#2]
For the following byte sequence '93010492C41043EA4CABB03E4655BE4CA8927EFDB1D0CF0000018AAD99F857' I receive at the end of the last number a letter 'n', which is unexpected:
[1, 4, [[67, 234, 76, 171, 176, 62, 70, 85, 190, 76, 168, 146, 126, 253, 177, 208], 1695129663575n]]
Hopefully you can help me.

Best Regards

**Comment by niranjannitesh** [comment]
I didn't think anyone else used it, I built it a while back for a personal project, I will check what's going on over the weekend.

**Comment by matthaeis** [comment]
Thanks for your fast reply and support.
While looking deeper at your code, I realized, that we referenced two libraries, which are able to handle message pack. And we used not yours but another one. So there is no issue at all. (Updating the other library to the latest version fixed the problem for us.)
